language: JAVA
script: mvn install
jdk:
  - oraclejdk8
cache:
    directories:
    - .autoconf
    - $HOME/.m2
before_install:
    -  "mkdir idea"
    -  "./download-unpack-intellij.sh 2018.3.5 idea idea-IC-183.5912.21 $HOME/.m2"
    -  "./install-intellij-libs.sh 2018.3.5 idea $HOME/.m2"
after_failure:
      - cat ./camel-idea-plugin/camel-idea-plugin/target/failsafe-reports/*.txt
      - cat ./camel-idea-plugin/camel-idea-plugin/target/surefire-reports/*.txt